### ISSUE TITLE
kaffeekasse geht nicht mehr bei ubuntu 22.04

### ISSUE THREAD

**Issue by AbdullahAbas01** [rojul/tally#1]
Hi,
ich bin ein Azubi in der Klara-Oppenheimer-Schule und wollte den Kaffeekasse-Server neu aufsetzten, da es zurzeit Probleme macht.
ich kenne mich mit Angular gar nicht aus und wollte fragen, da du den gemacht hast, ob du danach schauen kannst

MFG

**Comment by rojul** [comment]
Hallo Abdullah, gab es einen bestimmten Fehler? Ich habe ein nginx Image hinzugefügt, bei dem tally-web in Docker gebaut wird und in der Readme ein Beispiel für die Installation auf Ububtu 22 hinzugefügt. Ich hoffe das hilft :)

**Comment by AbdullahAbas01** [comment]
Vielen Dank für dein schnelle Antwort,

ich habe es gerade ausprobiert und funktioniert jetzt einwandfrei und die alte Datenbank zu kopieren hat auch funktioniert.

Grüße von Herr Schellenberger und der Systembetreuung
MFG
Abdullah Abas
